module Railway
  module Cli
    module Main
      HELP: ::String

      attr_accessor self.command: untyped

      def self.help: () -> untyped

      def self.control: (untyped commands) -> untyped
    end
  end
end
