module Railway
  #
  # Railway::Cli
  module Cli
    def self.state: () -> Hash[Symbol, untyped]

    def self.state=: (Hash[Symbol, untyped] state) -> Hash[Symbol, untyped]

    #
    # Railway::Cli::Main
    module Main
      HELP: ::String

      attr_accessor self.command: untyped

      def self.help: () -> untyped

      def self.control: (untyped commands) -> untyped
    end
  end
end
