# Описание 2
module Railway
  module Train
    #
    # Какое-то описание
    # TrainAbstract
    class TrainAbstract
      attr_reader type: ::Symbol

      attr_accessor number: ::String

      attr_accessor speed: ::Float

      attr_accessor wagons: ::Array[::String]

      attr_accessor route: ::Array[::String]

      def initialize: (::String _number, ::Array[::String] _wagons, ::Array[::String] _route) -> void
    end
  end
end
